"""Audit fixes: numeric types, indexes, and reference range

Revision ID: 71adc9dcc7cb
Revises: af144f1a4748
Create Date: 2026-07-25 02:10:41.483250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71adc9dcc7cb'
down_revision = 'af144f1a4748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('paid_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_patients_patient_code'), type_='unique')
        batch_op.create_index(batch_op.f('ix_patients_patient_code'), ['patient_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)

    with op.batch_alter_table('referral_commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('commission_amount')

    with op.batch_alter_table('referral_doctors', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.drop_column('hospital')
        batch_op.drop_column('name')

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_samples_barcode'), type_='unique')
        batch_op.create_index(batch_op.f('ix_samples_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_samples_status'), ['status'], unique=False)

    with op.batch_alter_table('test_order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_orders_status'), ['status'], unique=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_range', sa.String(length=255), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('reference_range')

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_orders_status'))

    with op.batch_alter_table('test_order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_status'))
        batch_op.drop_index(batch_op.f('ix_samples_barcode'))
        batch_op.create_unique_constraint(batch_op.f('uq_samples_barcode'), ['barcode'])

    with op.batch_alter_table('referral_doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('hospital', sa.VARCHAR(length=150), nullable=True))
        batch_op.alter_column('commission_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('referral_commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('amount')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_code'))
        batch_op.create_unique_constraint(batch_op.f('uq_patients_patient_code'), ['patient_code'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('paid_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
