"""Add appointment models and update referral doctor

Revision ID: af144f1a4748
Revises: c728ddf9ea4e
Create Date: 2026-03-11 03:07:19.862087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af144f1a4748'
down_revision = 'c728ddf9ea4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('patient_email', sa.String(length=100), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['referral_doctors.id'], name=op.f('fk_appointments_doctor_id_referral_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['referral_doctors.id'], name=op.f('fk_doctor_schedules_doctor_id_referral_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_schedules'))
    )
    with op.batch_alter_table('referral_doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_doctors', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('hospital_name')
        batch_op.drop_column('specialization')
        batch_op.drop_column('doctor_name')

    op.drop_table('doctor_schedules')
    op.drop_table('appointments')
    # ### end Alembic commands ###
