"""Add UUID to TestOrder and Barcode to Sample with naming convention

Revision ID: b6ff8bfe15ef
Revises: 21644f7c091c
Create Date: 2026-03-08 00:41:32.227146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ff8bfe15ef'
down_revision = '21644f7c091c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_patients_patient_code'), ['patient_code'])

    with op.batch_alter_table('test_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_test_categories_name'), ['name'])

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_test_orders_uuid'), ['uuid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_test_orders_uuid'), type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('test_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_test_categories_name'), type_='unique')

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_samples_barcode'), type_='unique')
        batch_op.drop_column('barcode')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patients_patient_code'), type_='unique')

    op.create_table('_alembic_tmp_samples',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('sample_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('collection_time', sa.DATETIME(), nullable=True),
    sa.Column('collector_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['test_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name=op.f('uq_samples_barcode'))
    )
    # ### end Alembic commands ###
