"""Add referral_id to test_orders

Revision ID: c728ddf9ea4e
Revises: b6ff8bfe15ef
Create Date: 2026-03-11 02:11:02.049685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c728ddf9ea4e'
down_revision = 'b6ff8bfe15ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_reagent_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_consumed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_test_reagent_consumption_inventory_item_id_inventory_items')),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_reagent_consumption_test_id_tests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_reagent_consumption'))
    )
    op.drop_table('_alembic_tmp_patients')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_patients_patient_code'), ['patient_code'])

    with op.batch_alter_table('referral_doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_referral_doctors_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_samples_barcode'), ['barcode'])

    with op.batch_alter_table('test_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_test_categories_name'), ['name'])

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_id', sa.Integer(), nullable=True))
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_test_orders_uuid'), ['uuid'])
        batch_op.create_foreign_key(batch_op.f('fk_test_orders_referral_id_referral_doctors'), 'referral_doctors', ['referral_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_test_orders_referral_id_referral_doctors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_test_orders_uuid'), type_='unique')
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('referral_id')

    with op.batch_alter_table('test_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_test_categories_name'), type_='unique')

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_samples_barcode'), type_='unique')

    with op.batch_alter_table('referral_doctors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_referral_doctors_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patients_patient_code'), type_='unique')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold')

    op.create_table('_alembic_tmp_patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=5), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_code', name=op.f('uq_patients_patient_code'))
    )
    op.drop_table('test_reagent_consumption')
    # ### end Alembic commands ###
